# Generated by Django 4.1.3 on 2022-11-14 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0002_alter_task_options_alter_task_deadline'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['is_done', '-created_at']},
        ),
    ]
